/**
 * ⚠️  WARNING: This file is auto-generated by the generate:interfaces script.
 * ⚠️  Do not manually modify this file as it will be overwritten on the next generation.
 * ⚠️  To update this interface, modify the corresponding DTO in the backend.
 */
export interface AthleteLiftRankingDto {
  userId: number
  firstName: string | null
  lastName: string | null
  currentClassTypeId: number | null
  liftType: {
    id: number
    name: string
    maxAmount: number
  }
  weight: number
  isPr: boolean
  videoUrl: string | null
}
