/**
 * ⚠️  WARNING: This file is auto-generated by the generate:interfaces script.
 * ⚠️  Do not manually modify this file as it will be overwritten on the next generation.
 * ⚠️  To update this interface, modify the corresponding DTO in the backend.
 */
export interface AthleteThrowOverallRankingDto {
  userId: number
  firstName: string | null
  lastName: string | null
  currentClassTypeId: number | null
  classType: {
    id: number
    name: string
  }
  throws: AthleteThrowRankingDto[]
  totalPoints: number
  usedThrowTypeIds: number[] // IDs of throw types used in totalPoints calculation
}
