/**
 * ⚠️  WARNING: This file is auto-generated by the generate:interfaces script.
 * ⚠️  Do not manually modify this file as it will be overwritten on the next generation.
 * ⚠️  To update this interface, modify the corresponding model in the backend.
 */

export interface AthleteThrow {
  id: number
  userId: number
  throwTypeId: number
  classTypeId: number
  gameId: number | null
  place: number
  isPr: boolean
  videoUrl: string | null
  score: string | null
  createdAt: string
  updatedAt: string | null
}
