/**
 * ⚠️  WARNING: This file is auto-generated by the generate:interfaces script.
 * ⚠️  Do not manually modify this file as it will be overwritten on the next generation.
 * ⚠️  To update this interface, modify the corresponding model in the backend.
 */

export interface ClassType {
  name: string
  createdAt: string
  updatedAt: string | null
}
