/**
 * ⚠️  WARNING: This file is auto-generated by the generate:interfaces script.
 * ⚠️  Do not manually modify this file as it will be overwritten on the next generation.
 * ⚠️  To update this interface, modify the corresponding model in the backend.
 */

export interface ThrowType {
  name: string
  weight: number
  maxDistance: number
  description: string | null
  classTypeIds: number[] | null
  createdAt: string
  updatedAt: string | null
}
