/**
 * ⚠️  WARNING: This file is auto-generated by the generate:interfaces script.
 * ⚠️  Do not manually modify this file as it will be overwritten on the next generation.
 * ⚠️  To update this interface, modify the corresponding model in the backend.
 */

export interface User {
  id: number
  firstName: string | null
  lastName: string | null
  email: string
  roleId: number | null
  currentClassTypeId: number | null
  passwordResetTokenExpiresAt: string | null
  failedLoginAttempts: number
  accountLockedUntil: string | null
  facebookId: string | null
  facebookUrl: string | null
  instagramUrl: string | null
  profileImageUrl: string | null
  height: number | null
  weight: number | null
  dateOfBirth: string | null
  state: string | null
  createdAt: string
  updatedAt: string | null
}
